#ifndef TIPODETOKEN_H
#define TIPODETOKEN_H


enum class TipoDeToken
{
    NUMERO_INTEIRO,
    NUMERO_REAL,
    IDENTIFICADOR,
    PALAVRA_CHAVE,
    OPERADOR_ARITMETICO,
    OPERADOR_LOGICO,
    OPERADOR_COMPARACAO,
    OPERADOR_ATRIBUICAO,
    OPERADOR_INCREMENTO,
    OPERADOR_DECREMENTO,
    OPERADOR_COMPOSTO,
    STRING_LITERAL,
    CARACTERE_LITERAL,
    COMENTARIO_LINHA,
    COMENTARIO_BLOCO,
    PONTUACAO,
    DESCONHECIDO
};

#endif // TIPODETOKEN_H
